### ISSUE TITLE
Migration of filles is incomplete

### ISSUE THREAD

**Issue by rikyfocil-old** [rikyfocil/BerryCloud#2]
Apparently the name field is missing on the migration of files and therefore is not on the database. This should be updated in a commit to allow the application to work.

**Comment by rikyfocil** [comment]
There is another inconsistency in the file migration where the name is a string. This will be fixed int he next commit. 

I will run a inconsistency check in the entire migrations and all the inconsistencies will be reported in this thread.

**Comment by rikyfocil-old** [comment]
There is a last problem here in the database diagram. This will be updated to reflect the laravel managed attributes such as the deleted properties in files and the email instead of username in users. The commit will be uploaded soon
